import math
from datetime import datetime, timedelta
from typing import List, Dict

LOCALITY_PROFILES = {
    "Mumbai, MH": {
        "base_demand": 4500,
        "temp_coef": 55,
        "humid_coef": 8,
        "wind_coef": -10,
        "lat": 19.08,
        "lng": 72.88,
        "base_temp": 28,
        "temp_range": 6,
    },
    "Delhi, DL": {
        "base_demand": 12000,
        "temp_coef": 90,
        "humid_coef": 6,
        "wind_coef": -20,
        "lat": 28.61,
        "lng": 77.21,
        "base_temp": 25,
        "temp_range": 16,
    },
    "Bengaluru, KA": {
        "base_demand": 8000,
        "temp_coef": 60,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 12.97,
        "lng": 77.59,
        "base_temp": 23,
        "temp_range": 5,
    },
    "Chennai, TN": {
        "base_demand": 6000,
        "temp_coef": 70,
        "humid_coef": 9,
        "wind_coef": -8,
        "lat": 13.08,
        "lng": 80.27,
        "base_temp": 30,
        "temp_range": 4,
    },
    "Kolkata, WB": {
        "base_demand": 5500,
        "temp_coef": 65,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 22.57,
        "lng": 88.36,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Hyderabad, TS": {
        "base_demand": 7000,
        "temp_coef": 72,
        "humid_coef": 6,
        "wind_coef": -14,
        "lat": 17.39,
        "lng": 78.49,
        "base_temp": 26,
        "temp_range": 8,
    },
    "Ahmedabad, GJ": {
        "base_demand": 5000,
        "temp_coef": 80,
        "humid_coef": 4,
        "wind_coef": -16,
        "lat": 23.03,
        "lng": 72.59,
        "base_temp": 27,
        "temp_range": 12,
    },
    "Pune, MH": {
        "base_demand": 5800,
        "temp_coef": 58,
        "humid_coef": 5,
        "wind_coef": -11,
        "lat": 18.52,
        "lng": 73.86,
        "base_temp": 25,
        "temp_range": 7,
    },
    "Jaipur, RJ": {
        "base_demand": 4200,
        "temp_coef": 82,
        "humid_coef": 4,
        "wind_coef": -15,
        "lat": 26.91,
        "lng": 75.79,
        "base_temp": 26,
        "temp_range": 15,
    },
    "Jodhpur, RJ": {
        "base_demand": 1800,
        "temp_coef": 85,
        "humid_coef": 3,
        "wind_coef": -14,
        "lat": 26.29,
        "lng": 73.02,
        "base_temp": 27,
        "temp_range": 16,
    },
    "Kota, RJ": {
        "base_demand": 1600,
        "temp_coef": 84,
        "humid_coef": 4,
        "wind_coef": -13,
        "lat": 25.18,
        "lng": 75.85,
        "base_temp": 27,
        "temp_range": 15,
    },
    "Bikaner, RJ": {
        "base_demand": 1200,
        "temp_coef": 88,
        "humid_coef": 3,
        "wind_coef": -12,
        "lat": 28.02,
        "lng": 73.31,
        "base_temp": 27,
        "temp_range": 17,
    },
    "Ajmer, RJ": {
        "base_demand": 1000,
        "temp_coef": 82,
        "humid_coef": 4,
        "wind_coef": -13,
        "lat": 26.45,
        "lng": 74.64,
        "base_temp": 26,
        "temp_range": 15,
    },
    "Udaipur, RJ": {
        "base_demand": 900,
        "temp_coef": 75,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 24.58,
        "lng": 73.69,
        "base_temp": 25,
        "temp_range": 13,
    },
    "Bhilwara, RJ": {
        "base_demand": 700,
        "temp_coef": 80,
        "humid_coef": 4,
        "wind_coef": -12,
        "lat": 25.35,
        "lng": 74.63,
        "base_temp": 26,
        "temp_range": 14,
    },
    "Alwar, RJ": {
        "base_demand": 700,
        "temp_coef": 83,
        "humid_coef": 4,
        "wind_coef": -14,
        "lat": 27.56,
        "lng": 76.6,
        "base_temp": 26,
        "temp_range": 15,
    },
    "Lucknow, UP": {
        "base_demand": 4000,
        "temp_coef": 85,
        "humid_coef": 6,
        "wind_coef": -18,
        "lat": 26.85,
        "lng": 80.95,
        "base_temp": 26,
        "temp_range": 14,
    },
    "Kanpur, UP": {
        "base_demand": 3500,
        "temp_coef": 86,
        "humid_coef": 6,
        "wind_coef": -17,
        "lat": 26.47,
        "lng": 80.35,
        "base_temp": 26,
        "temp_range": 14,
    },
    "Ghaziabad, UP": {
        "base_demand": 2800,
        "temp_coef": 88,
        "humid_coef": 6,
        "wind_coef": -19,
        "lat": 28.67,
        "lng": 77.45,
        "base_temp": 25,
        "temp_range": 15,
    },
    "Agra, UP": {
        "base_demand": 2200,
        "temp_coef": 87,
        "humid_coef": 5,
        "wind_coef": -16,
        "lat": 27.18,
        "lng": 78.02,
        "base_temp": 26,
        "temp_range": 15,
    },
    "Meerut, UP": {
        "base_demand": 2000,
        "temp_coef": 87,
        "humid_coef": 6,
        "wind_coef": -17,
        "lat": 28.98,
        "lng": 77.71,
        "base_temp": 25,
        "temp_range": 15,
    },
    "Varanasi, UP": {
        "base_demand": 1800,
        "temp_coef": 84,
        "humid_coef": 7,
        "wind_coef": -15,
        "lat": 25.32,
        "lng": 83.01,
        "base_temp": 27,
        "temp_range": 13,
    },
    "Allahabad, UP": {
        "base_demand": 1700,
        "temp_coef": 85,
        "humid_coef": 6,
        "wind_coef": -16,
        "lat": 25.43,
        "lng": 81.85,
        "base_temp": 26,
        "temp_range": 14,
    },
    "Bareilly, UP": {
        "base_demand": 1400,
        "temp_coef": 86,
        "humid_coef": 6,
        "wind_coef": -16,
        "lat": 28.36,
        "lng": 79.41,
        "base_temp": 25,
        "temp_range": 15,
    },
    "Moradabad, UP": {
        "base_demand": 1300,
        "temp_coef": 85,
        "humid_coef": 6,
        "wind_coef": -15,
        "lat": 28.84,
        "lng": 78.78,
        "base_temp": 25,
        "temp_range": 15,
    },
    "Aligarh, UP": {
        "base_demand": 1200,
        "temp_coef": 87,
        "humid_coef": 6,
        "wind_coef": -16,
        "lat": 27.88,
        "lng": 78.08,
        "base_temp": 26,
        "temp_range": 15,
    },
    "Gorakhpur, UP": {
        "base_demand": 1200,
        "temp_coef": 83,
        "humid_coef": 7,
        "wind_coef": -14,
        "lat": 26.76,
        "lng": 83.37,
        "base_temp": 26,
        "temp_range": 13,
    },
    "Saharanpur, UP": {
        "base_demand": 1100,
        "temp_coef": 86,
        "humid_coef": 6,
        "wind_coef": -15,
        "lat": 29.97,
        "lng": 77.55,
        "base_temp": 24,
        "temp_range": 16,
    },
    "Noida, UP": {
        "base_demand": 2500,
        "temp_coef": 88,
        "humid_coef": 6,
        "wind_coef": -19,
        "lat": 28.53,
        "lng": 77.39,
        "base_temp": 25,
        "temp_range": 15,
    },
    "Firozabad, UP": {
        "base_demand": 800,
        "temp_coef": 85,
        "humid_coef": 5,
        "wind_coef": -15,
        "lat": 27.15,
        "lng": 78.4,
        "base_temp": 26,
        "temp_range": 15,
    },
    "Loni, UP": {
        "base_demand": 900,
        "temp_coef": 87,
        "humid_coef": 6,
        "wind_coef": -17,
        "lat": 28.75,
        "lng": 77.29,
        "base_temp": 25,
        "temp_range": 15,
    },
    "Jhansi, UP": {
        "base_demand": 900,
        "temp_coef": 86,
        "humid_coef": 4,
        "wind_coef": -14,
        "lat": 25.45,
        "lng": 78.57,
        "base_temp": 27,
        "temp_range": 15,
    },
    "Muzaffarnagar, UP": {
        "base_demand": 900,
        "temp_coef": 86,
        "humid_coef": 6,
        "wind_coef": -15,
        "lat": 29.47,
        "lng": 77.71,
        "base_temp": 24,
        "temp_range": 16,
    },
    "Shahjahanpur, UP": {
        "base_demand": 700,
        "temp_coef": 85,
        "humid_coef": 6,
        "wind_coef": -15,
        "lat": 27.88,
        "lng": 79.91,
        "base_temp": 25,
        "temp_range": 14,
    },
    "Rampur, UP": {
        "base_demand": 700,
        "temp_coef": 85,
        "humid_coef": 6,
        "wind_coef": -15,
        "lat": 28.81,
        "lng": 79.03,
        "base_temp": 25,
        "temp_range": 15,
    },
    "Mathura, UP": {
        "base_demand": 800,
        "temp_coef": 87,
        "humid_coef": 5,
        "wind_coef": -15,
        "lat": 27.49,
        "lng": 77.67,
        "base_temp": 26,
        "temp_range": 15,
    },
    "Nagpur, MH": {
        "base_demand": 3200,
        "temp_coef": 75,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 21.14,
        "lng": 79.08,
        "base_temp": 28,
        "temp_range": 10,
    },
    "Thane, MH": {
        "base_demand": 3000,
        "temp_coef": 56,
        "humid_coef": 8,
        "wind_coef": -10,
        "lat": 19.22,
        "lng": 72.98,
        "base_temp": 28,
        "temp_range": 6,
    },
    "Pimpri-Chinchwad, MH": {
        "base_demand": 2800,
        "temp_coef": 57,
        "humid_coef": 5,
        "wind_coef": -11,
        "lat": 18.62,
        "lng": 73.8,
        "base_temp": 25,
        "temp_range": 7,
    },
    "Nashik, MH": {
        "base_demand": 2200,
        "temp_coef": 60,
        "humid_coef": 5,
        "wind_coef": -11,
        "lat": 19.99,
        "lng": 73.79,
        "base_temp": 24,
        "temp_range": 8,
    },
    "Kalyan-Dombivli, MH": {
        "base_demand": 2000,
        "temp_coef": 56,
        "humid_coef": 8,
        "wind_coef": -10,
        "lat": 19.23,
        "lng": 73.13,
        "base_temp": 28,
        "temp_range": 6,
    },
    "Vasai-Virar, MH": {
        "base_demand": 1800,
        "temp_coef": 56,
        "humid_coef": 8,
        "wind_coef": -10,
        "lat": 19.39,
        "lng": 72.82,
        "base_temp": 28,
        "temp_range": 6,
    },
    "Aurangabad, MH": {
        "base_demand": 1800,
        "temp_coef": 70,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 19.88,
        "lng": 75.34,
        "base_temp": 26,
        "temp_range": 9,
    },
    "Navi Mumbai, MH": {
        "base_demand": 2200,
        "temp_coef": 55,
        "humid_coef": 8,
        "wind_coef": -10,
        "lat": 19.04,
        "lng": 73.02,
        "base_temp": 28,
        "temp_range": 6,
    },
    "Solapur, MH": {
        "base_demand": 1500,
        "temp_coef": 72,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 17.69,
        "lng": 75.91,
        "base_temp": 27,
        "temp_range": 8,
    },
    "Amravati, MH": {
        "base_demand": 1100,
        "temp_coef": 74,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 20.93,
        "lng": 77.75,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Bhiwandi, MH": {
        "base_demand": 1200,
        "temp_coef": 56,
        "humid_coef": 8,
        "wind_coef": -10,
        "lat": 19.3,
        "lng": 73.06,
        "base_temp": 28,
        "temp_range": 6,
    },
    "Nanded, MH": {
        "base_demand": 900,
        "temp_coef": 72,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 19.16,
        "lng": 77.31,
        "base_temp": 27,
        "temp_range": 9,
    },
    "Kolhapur, MH": {
        "base_demand": 1100,
        "temp_coef": 62,
        "humid_coef": 6,
        "wind_coef": -11,
        "lat": 16.7,
        "lng": 74.24,
        "base_temp": 25,
        "temp_range": 6,
    },
    "Latur, MH": {
        "base_demand": 800,
        "temp_coef": 72,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 18.4,
        "lng": 76.56,
        "base_temp": 27,
        "temp_range": 9,
    },
    "Dhule, MH": {
        "base_demand": 700,
        "temp_coef": 73,
        "humid_coef": 4,
        "wind_coef": -12,
        "lat": 20.9,
        "lng": 74.78,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Ahmednagar, MH": {
        "base_demand": 900,
        "temp_coef": 68,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 19.09,
        "lng": 74.74,
        "base_temp": 25,
        "temp_range": 8,
    },
    "Chandrapur, MH": {
        "base_demand": 700,
        "temp_coef": 76,
        "humid_coef": 6,
        "wind_coef": -11,
        "lat": 19.96,
        "lng": 79.3,
        "base_temp": 28,
        "temp_range": 10,
    },
    "Parbhani, MH": {
        "base_demand": 600,
        "temp_coef": 72,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 19.27,
        "lng": 76.77,
        "base_temp": 27,
        "temp_range": 9,
    },
    "Malegaon, MH": {
        "base_demand": 700,
        "temp_coef": 72,
        "humid_coef": 5,
        "wind_coef": -11,
        "lat": 20.56,
        "lng": 74.52,
        "base_temp": 26,
        "temp_range": 9,
    },
    "Sangli-Miraj, MH": {
        "base_demand": 900,
        "temp_coef": 65,
        "humid_coef": 5,
        "wind_coef": -11,
        "lat": 16.85,
        "lng": 74.57,
        "base_temp": 26,
        "temp_range": 7,
    },
    "Ichalkaranji, MH": {
        "base_demand": 700,
        "temp_coef": 63,
        "humid_coef": 6,
        "wind_coef": -11,
        "lat": 16.7,
        "lng": 74.46,
        "base_temp": 25,
        "temp_range": 6,
    },
    "Ulhasnagar, MH": {
        "base_demand": 800,
        "temp_coef": 56,
        "humid_coef": 8,
        "wind_coef": -10,
        "lat": 19.22,
        "lng": 73.16,
        "base_temp": 28,
        "temp_range": 6,
    },
    "Indore, MP": {
        "base_demand": 2800,
        "temp_coef": 77,
        "humid_coef": 5,
        "wind_coef": -14,
        "lat": 22.72,
        "lng": 75.86,
        "base_temp": 26,
        "temp_range": 12,
    },
    "Bhopal, MP": {
        "base_demand": 2500,
        "temp_coef": 76,
        "humid_coef": 5,
        "wind_coef": -14,
        "lat": 23.26,
        "lng": 77.41,
        "base_temp": 25,
        "temp_range": 12,
    },
    "Jabalpur, MP": {
        "base_demand": 1800,
        "temp_coef": 75,
        "humid_coef": 6,
        "wind_coef": -13,
        "lat": 23.18,
        "lng": 79.95,
        "base_temp": 26,
        "temp_range": 12,
    },
    "Gwalior, MP": {
        "base_demand": 1700,
        "temp_coef": 83,
        "humid_coef": 5,
        "wind_coef": -15,
        "lat": 26.22,
        "lng": 78.18,
        "base_temp": 26,
        "temp_range": 15,
    },
    "Ujjain, MP": {
        "base_demand": 900,
        "temp_coef": 77,
        "humid_coef": 5,
        "wind_coef": -13,
        "lat": 23.18,
        "lng": 75.77,
        "base_temp": 26,
        "temp_range": 12,
    },
    "Bijapur, KA": {
        "base_demand": 700,
        "temp_coef": 73,
        "humid_coef": 4,
        "wind_coef": -12,
        "lat": 16.83,
        "lng": 75.72,
        "base_temp": 26,
        "temp_range": 8,
    },
    "Vadodara, GJ": {
        "base_demand": 3000,
        "temp_coef": 78,
        "humid_coef": 5,
        "wind_coef": -15,
        "lat": 22.31,
        "lng": 73.18,
        "base_temp": 27,
        "temp_range": 12,
    },
    "Rajkot, GJ": {
        "base_demand": 2200,
        "temp_coef": 80,
        "humid_coef": 4,
        "wind_coef": -16,
        "lat": 22.3,
        "lng": 70.8,
        "base_temp": 27,
        "temp_range": 12,
    },
    "Surat, GJ": {
        "base_demand": 3500,
        "temp_coef": 76,
        "humid_coef": 7,
        "wind_coef": -14,
        "lat": 21.17,
        "lng": 72.83,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Bhavnagar, GJ": {
        "base_demand": 1200,
        "temp_coef": 78,
        "humid_coef": 6,
        "wind_coef": -15,
        "lat": 21.76,
        "lng": 72.15,
        "base_temp": 27,
        "temp_range": 11,
    },
    "Jamnagar, GJ": {
        "base_demand": 1000,
        "temp_coef": 78,
        "humid_coef": 6,
        "wind_coef": -15,
        "lat": 22.47,
        "lng": 70.07,
        "base_temp": 27,
        "temp_range": 11,
    },
    "Junagadh, GJ": {
        "base_demand": 800,
        "temp_coef": 77,
        "humid_coef": 5,
        "wind_coef": -14,
        "lat": 21.52,
        "lng": 70.46,
        "base_temp": 27,
        "temp_range": 11,
    },
    "Visakhapatnam, AP": {
        "base_demand": 3500,
        "temp_coef": 68,
        "humid_coef": 8,
        "wind_coef": -10,
        "lat": 17.69,
        "lng": 83.22,
        "base_temp": 28,
        "temp_range": 6,
    },
    "Vijayawada, AP": {
        "base_demand": 2500,
        "temp_coef": 72,
        "humid_coef": 7,
        "wind_coef": -10,
        "lat": 16.51,
        "lng": 80.62,
        "base_temp": 29,
        "temp_range": 7,
    },
    "Guntur, AP": {
        "base_demand": 1800,
        "temp_coef": 73,
        "humid_coef": 7,
        "wind_coef": -10,
        "lat": 16.3,
        "lng": 80.44,
        "base_temp": 29,
        "temp_range": 7,
    },
    "Kurnool, AP": {
        "base_demand": 1200,
        "temp_coef": 74,
        "humid_coef": 5,
        "wind_coef": -11,
        "lat": 15.83,
        "lng": 78.04,
        "base_temp": 29,
        "temp_range": 8,
    },
    "Kadapa, AP": {
        "base_demand": 1000,
        "temp_coef": 74,
        "humid_coef": 5,
        "wind_coef": -10,
        "lat": 14.47,
        "lng": 78.82,
        "base_temp": 29,
        "temp_range": 8,
    },
    "Rajahmundry, AP": {
        "base_demand": 1200,
        "temp_coef": 70,
        "humid_coef": 8,
        "wind_coef": -9,
        "lat": 17.01,
        "lng": 81.8,
        "base_temp": 29,
        "temp_range": 6,
    },
    "Tirupati, AP": {
        "base_demand": 900,
        "temp_coef": 70,
        "humid_coef": 6,
        "wind_coef": -10,
        "lat": 13.63,
        "lng": 79.42,
        "base_temp": 28,
        "temp_range": 6,
    },
    "Coimbatore, TN": {
        "base_demand": 2800,
        "temp_coef": 65,
        "humid_coef": 6,
        "wind_coef": -10,
        "lat": 11.02,
        "lng": 76.96,
        "base_temp": 27,
        "temp_range": 4,
    },
    "Madurai, TN": {
        "base_demand": 2000,
        "temp_coef": 68,
        "humid_coef": 6,
        "wind_coef": -9,
        "lat": 9.93,
        "lng": 78.12,
        "base_temp": 30,
        "temp_range": 4,
    },
    "Tiruchirappalli, TN": {
        "base_demand": 1800,
        "temp_coef": 68,
        "humid_coef": 6,
        "wind_coef": -9,
        "lat": 10.79,
        "lng": 78.7,
        "base_temp": 30,
        "temp_range": 4,
    },
    "Salem, TN": {
        "base_demand": 1500,
        "temp_coef": 66,
        "humid_coef": 5,
        "wind_coef": -9,
        "lat": 11.66,
        "lng": 78.15,
        "base_temp": 29,
        "temp_range": 5,
    },
    "Tirunelveli, TN": {
        "base_demand": 1100,
        "temp_coef": 67,
        "humid_coef": 7,
        "wind_coef": -9,
        "lat": 8.73,
        "lng": 77.7,
        "base_temp": 29,
        "temp_range": 4,
    },
    "Ambattur, TN": {
        "base_demand": 900,
        "temp_coef": 68,
        "humid_coef": 8,
        "wind_coef": -8,
        "lat": 13.11,
        "lng": 80.15,
        "base_temp": 30,
        "temp_range": 4,
    },
    "Erode, TN": {
        "base_demand": 1000,
        "temp_coef": 67,
        "humid_coef": 5,
        "wind_coef": -9,
        "lat": 11.34,
        "lng": 77.73,
        "base_temp": 29,
        "temp_range": 5,
    },
    "Avadi, TN": {
        "base_demand": 700,
        "temp_coef": 68,
        "humid_coef": 8,
        "wind_coef": -8,
        "lat": 13.11,
        "lng": 80.1,
        "base_temp": 30,
        "temp_range": 4,
    },
    "Mysuru, KA": {
        "base_demand": 1800,
        "temp_coef": 60,
        "humid_coef": 5,
        "wind_coef": -11,
        "lat": 12.31,
        "lng": 76.66,
        "base_temp": 23,
        "temp_range": 5,
    },
    "Hubballi-Dharwad, KA": {
        "base_demand": 1400,
        "temp_coef": 67,
        "humid_coef": 4,
        "wind_coef": -12,
        "lat": 15.36,
        "lng": 75.14,
        "base_temp": 26,
        "temp_range": 6,
    },
    "Mangaluru, KA": {
        "base_demand": 1200,
        "temp_coef": 62,
        "humid_coef": 10,
        "wind_coef": -9,
        "lat": 12.91,
        "lng": 74.86,
        "base_temp": 27,
        "temp_range": 4,
    },
    "Belgaum, KA": {
        "base_demand": 1100,
        "temp_coef": 65,
        "humid_coef": 5,
        "wind_coef": -11,
        "lat": 15.85,
        "lng": 74.5,
        "base_temp": 24,
        "temp_range": 6,
    },
    "Gulbarga, KA": {
        "base_demand": 900,
        "temp_coef": 74,
        "humid_coef": 4,
        "wind_coef": -12,
        "lat": 17.33,
        "lng": 76.82,
        "base_temp": 27,
        "temp_range": 9,
    },
    "Shimoga, KA": {
        "base_demand": 700,
        "temp_coef": 62,
        "humid_coef": 7,
        "wind_coef": -10,
        "lat": 13.93,
        "lng": 75.56,
        "base_temp": 25,
        "temp_range": 5,
    },
    "Tumkur, KA": {
        "base_demand": 700,
        "temp_coef": 63,
        "humid_coef": 5,
        "wind_coef": -11,
        "lat": 13.34,
        "lng": 77.1,
        "base_temp": 24,
        "temp_range": 5,
    },
    "Bellary, KA": {
        "base_demand": 800,
        "temp_coef": 74,
        "humid_coef": 4,
        "wind_coef": -12,
        "lat": 15.14,
        "lng": 76.92,
        "base_temp": 28,
        "temp_range": 9,
    },
    "Kochi, KL": {
        "base_demand": 2200,
        "temp_coef": 58,
        "humid_coef": 10,
        "wind_coef": -8,
        "lat": 9.93,
        "lng": 76.26,
        "base_temp": 28,
        "temp_range": 3,
    },
    "Thiruvananthapuram, KL": {
        "base_demand": 1800,
        "temp_coef": 58,
        "humid_coef": 10,
        "wind_coef": -8,
        "lat": 8.52,
        "lng": 76.94,
        "base_temp": 28,
        "temp_range": 3,
    },
    "Kozhikode, KL": {
        "base_demand": 1200,
        "temp_coef": 58,
        "humid_coef": 10,
        "wind_coef": -8,
        "lat": 11.25,
        "lng": 75.78,
        "base_temp": 28,
        "temp_range": 3,
    },
    "Thrissur, KL": {
        "base_demand": 1000,
        "temp_coef": 58,
        "humid_coef": 10,
        "wind_coef": -8,
        "lat": 10.53,
        "lng": 76.22,
        "base_temp": 28,
        "temp_range": 3,
    },
    "Kollam, KL": {
        "base_demand": 900,
        "temp_coef": 58,
        "humid_coef": 10,
        "wind_coef": -8,
        "lat": 8.88,
        "lng": 76.59,
        "base_temp": 28,
        "temp_range": 3,
    },
    "Howrah, WB": {
        "base_demand": 2500,
        "temp_coef": 65,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 22.59,
        "lng": 88.31,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Durgapur, WB": {
        "base_demand": 1400,
        "temp_coef": 66,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 23.48,
        "lng": 87.31,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Asansol, WB": {
        "base_demand": 1400,
        "temp_coef": 66,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 23.68,
        "lng": 86.99,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Siliguri, WB": {
        "base_demand": 1100,
        "temp_coef": 62,
        "humid_coef": 8,
        "wind_coef": -11,
        "lat": 26.72,
        "lng": 88.43,
        "base_temp": 24,
        "temp_range": 11,
    },
    "Rajpur Sonarpur, WB": {
        "base_demand": 800,
        "temp_coef": 64,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 22.44,
        "lng": 88.39,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Bhatpara, WB": {
        "base_demand": 700,
        "temp_coef": 64,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 22.87,
        "lng": 88.41,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Panihati, WB": {
        "base_demand": 700,
        "temp_coef": 64,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 22.69,
        "lng": 88.37,
        "base_temp": 27,
        "temp_range": 10,
    },
    "South Dumdum, WB": {
        "base_demand": 700,
        "temp_coef": 64,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 22.63,
        "lng": 88.4,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Kamarhati, WB": {
        "base_demand": 700,
        "temp_coef": 64,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 22.67,
        "lng": 88.37,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Bardhaman, WB": {
        "base_demand": 900,
        "temp_coef": 65,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 23.23,
        "lng": 87.86,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Kulti, WB": {
        "base_demand": 600,
        "temp_coef": 65,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 23.73,
        "lng": 86.85,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Kharagpur, WB": {
        "base_demand": 700,
        "temp_coef": 64,
        "humid_coef": 7,
        "wind_coef": -11,
        "lat": 22.33,
        "lng": 87.32,
        "base_temp": 27,
        "temp_range": 10,
    },
    "Ranchi, JH": {
        "base_demand": 1800,
        "temp_coef": 70,
        "humid_coef": 6,
        "wind_coef": -12,
        "lat": 23.36,
        "lng": 85.33,
        "base_temp": 24,
        "temp_range": 11,
    },
    "Dhanbad, JH": {
        "base_demand": 1600,
        "temp_coef": 68,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 23.8,
        "lng": 86.43,
        "base_temp": 26,
        "temp_range": 11,
    },
    "Jamshedpur, JH": {
        "base_demand": 1800,
        "temp_coef": 70,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 22.8,
        "lng": 86.19,
        "base_temp": 26,
        "temp_range": 11,
    },
    "Bokaro, JH": {
        "base_demand": 1000,
        "temp_coef": 68,
        "humid_coef": 7,
        "wind_coef": -12,
        "lat": 23.67,
        "lng": 85.98,
        "base_temp": 26,
        "temp_range": 11,
    },
    "Bhubaneswar, OD": {
        "base_demand": 2000,
        "temp_coef": 70,
        "humid_coef": 8,
        "wind_coef": -10,
        "lat": 20.3,
        "lng": 85.82,
        "base_temp": 28,
        "temp_range": 8,
    },
    "Cuttack, OD": {
        "base_demand": 1400,
        "temp_coef": 70,
        "humid_coef": 8,
        "wind_coef": -10,
        "lat": 20.46,
        "lng": 85.88,
        "base_temp": 28,
        "temp_range": 8,
    },
    "Brahmapur, OD": {
        "base_demand": 700,
        "temp_coef": 68,
        "humid_coef": 8,
        "wind_coef": -9,
        "lat": 19.31,
        "lng": 84.79,
        "base_temp": 28,
        "temp_range": 7,
    },
    "Gopalpur, OD": {
        "base_demand": 500,
        "temp_coef": 67,
        "humid_coef": 9,
        "wind_coef": -9,
        "lat": 19.26,
        "lng": 84.89,
        "base_temp": 28,
        "temp_range": 6,
    },
    "Patna, BR": {
        "base_demand": 2500,
        "temp_coef": 82,
        "humid_coef": 7,
        "wind_coef": -16,
        "lat": 25.6,
        "lng": 85.1,
        "base_temp": 27,
        "temp_range": 13,
    },
    "Gaya, BR": {
        "base_demand": 800,
        "temp_coef": 80,
        "humid_coef": 6,
        "wind_coef": -14,
        "lat": 24.8,
        "lng": 85.0,
        "base_temp": 27,
        "temp_range": 13,
    },
    "Muzaffarpur, BR": {
        "base_demand": 800,
        "temp_coef": 81,
        "humid_coef": 7,
        "wind_coef": -15,
        "lat": 26.12,
        "lng": 85.39,
        "base_temp": 26,
        "temp_range": 13,
    },
    "Bhagalpur, BR": {
        "base_demand": 700,
        "temp_coef": 80,
        "humid_coef": 7,
        "wind_coef": -14,
        "lat": 25.24,
        "lng": 87.01,
        "base_temp": 26,
        "temp_range": 13,
    },
    "Raipur, CG": {
        "base_demand": 2000,
        "temp_coef": 74,
        "humid_coef": 6,
        "wind_coef": -12,
        "lat": 21.25,
        "lng": 81.63,
        "base_temp": 27,
        "temp_range": 11,
    },
    "Bhilai, CG": {
        "base_demand": 1500,
        "temp_coef": 74,
        "humid_coef": 6,
        "wind_coef": -12,
        "lat": 21.21,
        "lng": 81.38,
        "base_temp": 27,
        "temp_range": 11,
    },
    "Korba, CG": {
        "base_demand": 700,
        "temp_coef": 73,
        "humid_coef": 6,
        "wind_coef": -11,
        "lat": 22.35,
        "lng": 82.7,
        "base_temp": 27,
        "temp_range": 11,
    },
    "Bilaspur, CG": {
        "base_demand": 900,
        "temp_coef": 74,
        "humid_coef": 6,
        "wind_coef": -12,
        "lat": 22.08,
        "lng": 82.15,
        "base_temp": 27,
        "temp_range": 11,
    },
    "Ludhiana, PB": {
        "base_demand": 2800,
        "temp_coef": 85,
        "humid_coef": 5,
        "wind_coef": -17,
        "lat": 30.9,
        "lng": 75.86,
        "base_temp": 23,
        "temp_range": 17,
    },
    "Amritsar, PB": {
        "base_demand": 2000,
        "temp_coef": 84,
        "humid_coef": 5,
        "wind_coef": -17,
        "lat": 31.64,
        "lng": 74.87,
        "base_temp": 22,
        "temp_range": 17,
    },
    "Jalandhar, PB": {
        "base_demand": 1800,
        "temp_coef": 84,
        "humid_coef": 5,
        "wind_coef": -17,
        "lat": 31.33,
        "lng": 75.58,
        "base_temp": 23,
        "temp_range": 17,
    },
    "Patiala, PB": {
        "base_demand": 1200,
        "temp_coef": 84,
        "humid_coef": 5,
        "wind_coef": -16,
        "lat": 30.34,
        "lng": 76.39,
        "base_temp": 24,
        "temp_range": 17,
    },
    "Faridabad, HR": {
        "base_demand": 2500,
        "temp_coef": 88,
        "humid_coef": 6,
        "wind_coef": -18,
        "lat": 28.41,
        "lng": 77.31,
        "base_temp": 25,
        "temp_range": 15,
    },
    "Gurgaon, HR": {
        "base_demand": 3000,
        "temp_coef": 88,
        "humid_coef": 6,
        "wind_coef": -18,
        "lat": 28.46,
        "lng": 77.03,
        "base_temp": 25,
        "temp_range": 15,
    },
    "Rohtak, HR": {
        "base_demand": 900,
        "temp_coef": 87,
        "humid_coef": 5,
        "wind_coef": -17,
        "lat": 28.89,
        "lng": 76.59,
        "base_temp": 25,
        "temp_range": 16,
    },
    "Chandigarh, CH": {
        "base_demand": 1800,
        "temp_coef": 83,
        "humid_coef": 5,
        "wind_coef": -16,
        "lat": 30.74,
        "lng": 76.79,
        "base_temp": 23,
        "temp_range": 16,
    },
    "Guwahati, AS": {
        "base_demand": 1500,
        "temp_coef": 65,
        "humid_coef": 9,
        "wind_coef": -10,
        "lat": 26.14,
        "lng": 91.74,
        "base_temp": 24,
        "temp_range": 9,
    },
    "Dispur, AS": {
        "base_demand": 600,
        "temp_coef": 65,
        "humid_coef": 9,
        "wind_coef": -10,
        "lat": 26.14,
        "lng": 91.78,
        "base_temp": 24,
        "temp_range": 9,
    },
    "Agartala, TR": {
        "base_demand": 500,
        "temp_coef": 63,
        "humid_coef": 9,
        "wind_coef": -9,
        "lat": 23.83,
        "lng": 91.28,
        "base_temp": 25,
        "temp_range": 8,
    },
    "Imphal, MN": {
        "base_demand": 400,
        "temp_coef": 60,
        "humid_coef": 8,
        "wind_coef": -9,
        "lat": 24.82,
        "lng": 93.94,
        "base_temp": 22,
        "temp_range": 10,
    },
    "Itanagar, AR": {
        "base_demand": 200,
        "temp_coef": 55,
        "humid_coef": 9,
        "wind_coef": -8,
        "lat": 27.1,
        "lng": 93.62,
        "base_temp": 20,
        "temp_range": 9,
    },
    "Kohima, NL": {
        "base_demand": 200,
        "temp_coef": 52,
        "humid_coef": 8,
        "wind_coef": -8,
        "lat": 25.67,
        "lng": 94.11,
        "base_temp": 18,
        "temp_range": 9,
    },
    "Aizawl, MZ": {
        "base_demand": 200,
        "temp_coef": 52,
        "humid_coef": 9,
        "wind_coef": -8,
        "lat": 23.72,
        "lng": 92.72,
        "base_temp": 20,
        "temp_range": 9,
    },
    "Srinagar, JK": {
        "base_demand": 1500,
        "temp_coef": 70,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 34.08,
        "lng": 74.8,
        "base_temp": 13,
        "temp_range": 18,
    },
    "Jammu, JK": {
        "base_demand": 1100,
        "temp_coef": 78,
        "humid_coef": 5,
        "wind_coef": -13,
        "lat": 32.73,
        "lng": 74.87,
        "base_temp": 22,
        "temp_range": 17,
    },
    "Dehradun, UK": {
        "base_demand": 1200,
        "temp_coef": 72,
        "humid_coef": 6,
        "wind_coef": -12,
        "lat": 30.32,
        "lng": 78.03,
        "base_temp": 20,
        "temp_range": 14,
    },
    "Shimla, HP": {
        "base_demand": 500,
        "temp_coef": 60,
        "humid_coef": 6,
        "wind_coef": -10,
        "lat": 31.1,
        "lng": 77.17,
        "base_temp": 12,
        "temp_range": 14,
    },
    "Gangtok, SK": {
        "base_demand": 200,
        "temp_coef": 50,
        "humid_coef": 7,
        "wind_coef": -8,
        "lat": 27.33,
        "lng": 88.61,
        "base_temp": 14,
        "temp_range": 10,
    },
    "Warangal, TS": {
        "base_demand": 1500,
        "temp_coef": 72,
        "humid_coef": 6,
        "wind_coef": -12,
        "lat": 18.0,
        "lng": 79.58,
        "base_temp": 27,
        "temp_range": 9,
    },
    "Nizamabad, TS": {
        "base_demand": 700,
        "temp_coef": 72,
        "humid_coef": 5,
        "wind_coef": -12,
        "lat": 18.67,
        "lng": 78.1,
        "base_temp": 27,
        "temp_range": 9,
    },
    "Panaji, GA": {
        "base_demand": 600,
        "temp_coef": 58,
        "humid_coef": 10,
        "wind_coef": -9,
        "lat": 15.5,
        "lng": 73.83,
        "base_temp": 27,
        "temp_range": 4,
    },
    "Port Blair, AN": {
        "base_demand": 200,
        "temp_coef": 52,
        "humid_coef": 11,
        "wind_coef": -8,
        "lat": 11.66,
        "lng": 92.74,
        "base_temp": 29,
        "temp_range": 2,
    },
}


def seeded_random(seed: float) -> float:
    x = math.sin(seed) * 10000
    return x - math.floor(x)


def generate_weather(locality: str, date: datetime, seed: int) -> Dict:
    profile = LOCALITY_PROFILES.get(locality)
    if not profile:
        return {"temperature": 25, "humidity": 60, "wind_speed": 10}

    month = date.month
    seasonal_temp = math.sin(((month - 3) * math.pi) / 6) * profile["temp_range"]
    temperature = profile["base_temp"] + seasonal_temp + (seeded_random(seed) - 0.5) * 6

    monsoon_humid = 20 if 5 <= month <= 8 else 0
    humidity = (
        55
        + monsoon_humid
        + math.sin((month * math.pi) / 3) * 15
        + (seeded_random(seed + 1) - 0.5) * 20
    )
    wind_speed = 10 + (seeded_random(seed + 2) - 0.5) * 18

    return {
        "temperature": round(temperature * 10) / 10,
        "humidity": min(100, max(20, round(humidity))),
        "wind_speed": max(0, round(wind_speed * 10) / 10),
    }


def generate_historical_data(locality: str) -> List[Dict]:
    profile = LOCALITY_PROFILES.get(locality)
    if not profile:
        return []

    records = []
    start = datetime(2021, 1, 1)
    end = datetime(2026, 3, 30)

    current = start
    day_of_year = 0
    while current <= end:
        seed = day_of_year * 17 + 31
        weather = generate_weather(locality, current, seed)

        dow = current.weekday()
        is_weekend = dow >= 5
        weekend_factor = 0.88 if is_weekend else 1.0
        noise = (seeded_random(day_of_year * 13 + 7) - 0.5) * 300
        year_trend = (current.year - 2021) * 60

        demand = (
            profile["base_demand"]
            + profile["temp_coef"] * weather["temperature"]
            + profile["humid_coef"] * weather["humidity"]
            + profile["wind_coef"] * weather["wind_speed"]
            + year_trend
            + noise
        )

        final_demand = max(800, round(demand * weekend_factor))

        records.append(
            {
                "date": current.strftime("%Y-%m-%d"),
                "demand_mw": final_demand,
                "temperature": weather["temperature"],
                "humidity": weather["humidity"],
                "wind_speed": weather["wind_speed"],
                "locality": locality,
            }
        )

        current += timedelta(days=1)
        day_of_year += 1

    return records


def get_locality_stats(records: List[Dict]) -> Dict:
    if not records:
        return {"avg_demand": 0, "peak_demand": 0, "min_demand": 0, "data_points": 0}

    demands = [r["demand_mw"] for r in records]
    return {
        "avg_demand": round(sum(demands) / len(demands)),
        "peak_demand": max(demands),
        "min_demand": min(demands),
        "data_points": len(demands),
    }


def get_localities() -> List[str]:
    return sorted(LOCALITY_PROFILES.keys())


def get_locality_coords() -> Dict[str, List[float]]:
    return {k: [v["lat"], v["lng"]] for k, v in LOCALITY_PROFILES.items()}
