export interface HistoricalRecord {
  date: string;
  demand_mw: number;
  temperature: number;
  humidity: number;
  wind_speed: number;
  locality: string;
}

const LOCALITY_PROFILES: Record<
  string,
  {
    baseDemand: number;
    tempCoef: number;
    humidCoef: number;
    windCoef: number;
    lat: number;
    lng: number;
    timezone: string;
    baseTemp: number;
    tempRange: number;
  }
> = {
  // --- Original 8 cities ---
  "Mumbai, MH": {
    baseDemand: 4500,
    tempCoef: 55,
    humidCoef: 8,
    windCoef: -10,
    lat: 19.08,
    lng: 72.88,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 6,
  },
  "Delhi, DL": {
    baseDemand: 12000,
    tempCoef: 90,
    humidCoef: 6,
    windCoef: -20,
    lat: 28.61,
    lng: 77.21,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 16,
  },
  "Bengaluru, KA": {
    baseDemand: 8000,
    tempCoef: 60,
    humidCoef: 5,
    windCoef: -12,
    lat: 12.97,
    lng: 77.59,
    timezone: "IST",
    baseTemp: 23,
    tempRange: 5,
  },
  "Chennai, TN": {
    baseDemand: 6000,
    tempCoef: 70,
    humidCoef: 9,
    windCoef: -8,
    lat: 13.08,
    lng: 80.27,
    timezone: "IST",
    baseTemp: 30,
    tempRange: 4,
  },
  "Kolkata, WB": {
    baseDemand: 5500,
    tempCoef: 65,
    humidCoef: 7,
    windCoef: -12,
    lat: 22.57,
    lng: 88.36,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Hyderabad, TS": {
    baseDemand: 7000,
    tempCoef: 72,
    humidCoef: 6,
    windCoef: -14,
    lat: 17.39,
    lng: 78.49,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 8,
  },
  "Ahmedabad, GJ": {
    baseDemand: 5000,
    tempCoef: 80,
    humidCoef: 4,
    windCoef: -16,
    lat: 23.03,
    lng: 72.59,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 12,
  },
  "Pune, MH": {
    baseDemand: 5800,
    tempCoef: 58,
    humidCoef: 5,
    windCoef: -11,
    lat: 18.52,
    lng: 73.86,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 7,
  },

  // --- Rajasthan ---
  "Jaipur, RJ": {
    baseDemand: 4200,
    tempCoef: 82,
    humidCoef: 4,
    windCoef: -15,
    lat: 26.91,
    lng: 75.79,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 15,
  },
  "Jodhpur, RJ": {
    baseDemand: 1800,
    tempCoef: 85,
    humidCoef: 3,
    windCoef: -14,
    lat: 26.29,
    lng: 73.02,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 16,
  },
  "Kota, RJ": {
    baseDemand: 1600,
    tempCoef: 84,
    humidCoef: 4,
    windCoef: -13,
    lat: 25.18,
    lng: 75.85,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 15,
  },
  "Bikaner, RJ": {
    baseDemand: 1200,
    tempCoef: 88,
    humidCoef: 3,
    windCoef: -12,
    lat: 28.02,
    lng: 73.31,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 17,
  },
  "Ajmer, RJ": {
    baseDemand: 1000,
    tempCoef: 82,
    humidCoef: 4,
    windCoef: -13,
    lat: 26.45,
    lng: 74.64,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 15,
  },
  "Udaipur, RJ": {
    baseDemand: 900,
    tempCoef: 75,
    humidCoef: 5,
    windCoef: -12,
    lat: 24.58,
    lng: 73.69,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 13,
  },
  "Bhilwara, RJ": {
    baseDemand: 700,
    tempCoef: 80,
    humidCoef: 4,
    windCoef: -12,
    lat: 25.35,
    lng: 74.63,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 14,
  },
  "Alwar, RJ": {
    baseDemand: 700,
    tempCoef: 83,
    humidCoef: 4,
    windCoef: -14,
    lat: 27.56,
    lng: 76.6,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 15,
  },

  // --- Uttar Pradesh ---
  "Lucknow, UP": {
    baseDemand: 4000,
    tempCoef: 85,
    humidCoef: 6,
    windCoef: -18,
    lat: 26.85,
    lng: 80.95,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 14,
  },
  "Kanpur, UP": {
    baseDemand: 3500,
    tempCoef: 86,
    humidCoef: 6,
    windCoef: -17,
    lat: 26.47,
    lng: 80.35,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 14,
  },
  "Ghaziabad, UP": {
    baseDemand: 2800,
    tempCoef: 88,
    humidCoef: 6,
    windCoef: -19,
    lat: 28.67,
    lng: 77.45,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 15,
  },
  "Agra, UP": {
    baseDemand: 2200,
    tempCoef: 87,
    humidCoef: 5,
    windCoef: -16,
    lat: 27.18,
    lng: 78.02,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 15,
  },
  "Meerut, UP": {
    baseDemand: 2000,
    tempCoef: 87,
    humidCoef: 6,
    windCoef: -17,
    lat: 28.98,
    lng: 77.71,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 15,
  },
  "Varanasi, UP": {
    baseDemand: 1800,
    tempCoef: 84,
    humidCoef: 7,
    windCoef: -15,
    lat: 25.32,
    lng: 83.01,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 13,
  },
  "Allahabad, UP": {
    baseDemand: 1700,
    tempCoef: 85,
    humidCoef: 6,
    windCoef: -16,
    lat: 25.43,
    lng: 81.85,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 14,
  },
  "Bareilly, UP": {
    baseDemand: 1400,
    tempCoef: 86,
    humidCoef: 6,
    windCoef: -16,
    lat: 28.36,
    lng: 79.41,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 15,
  },
  "Moradabad, UP": {
    baseDemand: 1300,
    tempCoef: 85,
    humidCoef: 6,
    windCoef: -15,
    lat: 28.84,
    lng: 78.78,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 15,
  },
  "Aligarh, UP": {
    baseDemand: 1200,
    tempCoef: 87,
    humidCoef: 6,
    windCoef: -16,
    lat: 27.88,
    lng: 78.08,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 15,
  },
  "Gorakhpur, UP": {
    baseDemand: 1200,
    tempCoef: 83,
    humidCoef: 7,
    windCoef: -14,
    lat: 26.76,
    lng: 83.37,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 13,
  },
  "Saharanpur, UP": {
    baseDemand: 1100,
    tempCoef: 86,
    humidCoef: 6,
    windCoef: -15,
    lat: 29.97,
    lng: 77.55,
    timezone: "IST",
    baseTemp: 24,
    tempRange: 16,
  },
  "Noida, UP": {
    baseDemand: 2500,
    tempCoef: 88,
    humidCoef: 6,
    windCoef: -19,
    lat: 28.53,
    lng: 77.39,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 15,
  },
  "Firozabad, UP": {
    baseDemand: 800,
    tempCoef: 85,
    humidCoef: 5,
    windCoef: -15,
    lat: 27.15,
    lng: 78.4,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 15,
  },
  "Loni, UP": {
    baseDemand: 900,
    tempCoef: 87,
    humidCoef: 6,
    windCoef: -17,
    lat: 28.75,
    lng: 77.29,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 15,
  },
  "Jhansi, UP": {
    baseDemand: 900,
    tempCoef: 86,
    humidCoef: 4,
    windCoef: -14,
    lat: 25.45,
    lng: 78.57,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 15,
  },
  "Muzaffarnagar, UP": {
    baseDemand: 900,
    tempCoef: 86,
    humidCoef: 6,
    windCoef: -15,
    lat: 29.47,
    lng: 77.71,
    timezone: "IST",
    baseTemp: 24,
    tempRange: 16,
  },
  "Shahjahanpur, UP": {
    baseDemand: 700,
    tempCoef: 85,
    humidCoef: 6,
    windCoef: -15,
    lat: 27.88,
    lng: 79.91,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 14,
  },
  "Rampur, UP": {
    baseDemand: 700,
    tempCoef: 85,
    humidCoef: 6,
    windCoef: -15,
    lat: 28.81,
    lng: 79.03,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 15,
  },
  "Mathura, UP": {
    baseDemand: 800,
    tempCoef: 87,
    humidCoef: 5,
    windCoef: -15,
    lat: 27.49,
    lng: 77.67,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 15,
  },

  // --- Maharashtra ---
  "Nagpur, MH": {
    baseDemand: 3200,
    tempCoef: 75,
    humidCoef: 5,
    windCoef: -12,
    lat: 21.14,
    lng: 79.08,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 10,
  },
  "Thane, MH": {
    baseDemand: 3000,
    tempCoef: 56,
    humidCoef: 8,
    windCoef: -10,
    lat: 19.22,
    lng: 72.98,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 6,
  },
  "Pimpri-Chinchwad, MH": {
    baseDemand: 2800,
    tempCoef: 57,
    humidCoef: 5,
    windCoef: -11,
    lat: 18.62,
    lng: 73.8,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 7,
  },
  "Nashik, MH": {
    baseDemand: 2200,
    tempCoef: 60,
    humidCoef: 5,
    windCoef: -11,
    lat: 19.99,
    lng: 73.79,
    timezone: "IST",
    baseTemp: 24,
    tempRange: 8,
  },
  "Kalyan-Dombivli, MH": {
    baseDemand: 2000,
    tempCoef: 56,
    humidCoef: 8,
    windCoef: -10,
    lat: 19.23,
    lng: 73.13,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 6,
  },
  "Vasai-Virar, MH": {
    baseDemand: 1800,
    tempCoef: 56,
    humidCoef: 8,
    windCoef: -10,
    lat: 19.39,
    lng: 72.82,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 6,
  },
  "Aurangabad, MH": {
    baseDemand: 1800,
    tempCoef: 70,
    humidCoef: 5,
    windCoef: -12,
    lat: 19.88,
    lng: 75.34,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 9,
  },
  "Navi Mumbai, MH": {
    baseDemand: 2200,
    tempCoef: 55,
    humidCoef: 8,
    windCoef: -10,
    lat: 19.04,
    lng: 73.02,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 6,
  },
  "Solapur, MH": {
    baseDemand: 1500,
    tempCoef: 72,
    humidCoef: 5,
    windCoef: -12,
    lat: 17.69,
    lng: 75.91,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 8,
  },
  "Amravati, MH": {
    baseDemand: 1100,
    tempCoef: 74,
    humidCoef: 5,
    windCoef: -12,
    lat: 20.93,
    lng: 77.75,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Bhiwandi, MH": {
    baseDemand: 1200,
    tempCoef: 56,
    humidCoef: 8,
    windCoef: -10,
    lat: 19.3,
    lng: 73.06,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 6,
  },
  "Nanded, MH": {
    baseDemand: 900,
    tempCoef: 72,
    humidCoef: 5,
    windCoef: -12,
    lat: 19.16,
    lng: 77.31,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 9,
  },
  "Kolhapur, MH": {
    baseDemand: 1100,
    tempCoef: 62,
    humidCoef: 6,
    windCoef: -11,
    lat: 16.7,
    lng: 74.24,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 6,
  },
  "Latur, MH": {
    baseDemand: 800,
    tempCoef: 72,
    humidCoef: 5,
    windCoef: -12,
    lat: 18.4,
    lng: 76.56,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 9,
  },
  "Dhule, MH": {
    baseDemand: 700,
    tempCoef: 73,
    humidCoef: 4,
    windCoef: -12,
    lat: 20.9,
    lng: 74.78,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Ahmednagar, MH": {
    baseDemand: 900,
    tempCoef: 68,
    humidCoef: 5,
    windCoef: -12,
    lat: 19.09,
    lng: 74.74,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 8,
  },
  "Chandrapur, MH": {
    baseDemand: 700,
    tempCoef: 76,
    humidCoef: 6,
    windCoef: -11,
    lat: 19.96,
    lng: 79.3,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 10,
  },
  "Parbhani, MH": {
    baseDemand: 600,
    tempCoef: 72,
    humidCoef: 5,
    windCoef: -12,
    lat: 19.27,
    lng: 76.77,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 9,
  },
  "Malegaon, MH": {
    baseDemand: 700,
    tempCoef: 72,
    humidCoef: 5,
    windCoef: -11,
    lat: 20.56,
    lng: 74.52,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 9,
  },
  "Sangli-Miraj, MH": {
    baseDemand: 900,
    tempCoef: 65,
    humidCoef: 5,
    windCoef: -11,
    lat: 16.85,
    lng: 74.57,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 7,
  },
  "Ichalkaranji, MH": {
    baseDemand: 700,
    tempCoef: 63,
    humidCoef: 6,
    windCoef: -11,
    lat: 16.7,
    lng: 74.46,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 6,
  },
  "Ulhasnagar, MH": {
    baseDemand: 800,
    tempCoef: 56,
    humidCoef: 8,
    windCoef: -10,
    lat: 19.22,
    lng: 73.16,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 6,
  },

  // --- Madhya Pradesh ---
  "Indore, MP": {
    baseDemand: 2800,
    tempCoef: 77,
    humidCoef: 5,
    windCoef: -14,
    lat: 22.72,
    lng: 75.86,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 12,
  },
  "Bhopal, MP": {
    baseDemand: 2500,
    tempCoef: 76,
    humidCoef: 5,
    windCoef: -14,
    lat: 23.26,
    lng: 77.41,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 12,
  },
  "Jabalpur, MP": {
    baseDemand: 1800,
    tempCoef: 75,
    humidCoef: 6,
    windCoef: -13,
    lat: 23.18,
    lng: 79.95,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 12,
  },
  "Gwalior, MP": {
    baseDemand: 1700,
    tempCoef: 83,
    humidCoef: 5,
    windCoef: -15,
    lat: 26.22,
    lng: 78.18,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 15,
  },
  "Ujjain, MP": {
    baseDemand: 900,
    tempCoef: 77,
    humidCoef: 5,
    windCoef: -13,
    lat: 23.18,
    lng: 75.77,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 12,
  },
  "Bijapur, KA": {
    baseDemand: 700,
    tempCoef: 73,
    humidCoef: 4,
    windCoef: -12,
    lat: 16.83,
    lng: 75.72,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 8,
  },

  // --- Gujarat ---
  "Vadodara, GJ": {
    baseDemand: 3000,
    tempCoef: 78,
    humidCoef: 5,
    windCoef: -15,
    lat: 22.31,
    lng: 73.18,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 12,
  },
  "Rajkot, GJ": {
    baseDemand: 2200,
    tempCoef: 80,
    humidCoef: 4,
    windCoef: -16,
    lat: 22.3,
    lng: 70.8,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 12,
  },
  "Surat, GJ": {
    baseDemand: 3500,
    tempCoef: 76,
    humidCoef: 7,
    windCoef: -14,
    lat: 21.17,
    lng: 72.83,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Bhavnagar, GJ": {
    baseDemand: 1200,
    tempCoef: 78,
    humidCoef: 6,
    windCoef: -15,
    lat: 21.76,
    lng: 72.15,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 11,
  },
  "Jamnagar, GJ": {
    baseDemand: 1000,
    tempCoef: 78,
    humidCoef: 6,
    windCoef: -15,
    lat: 22.47,
    lng: 70.07,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 11,
  },
  "Junagadh, GJ": {
    baseDemand: 800,
    tempCoef: 77,
    humidCoef: 5,
    windCoef: -14,
    lat: 21.52,
    lng: 70.46,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 11,
  },

  // --- Andhra Pradesh ---
  "Visakhapatnam, AP": {
    baseDemand: 3500,
    tempCoef: 68,
    humidCoef: 8,
    windCoef: -10,
    lat: 17.69,
    lng: 83.22,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 6,
  },
  "Vijayawada, AP": {
    baseDemand: 2500,
    tempCoef: 72,
    humidCoef: 7,
    windCoef: -10,
    lat: 16.51,
    lng: 80.62,
    timezone: "IST",
    baseTemp: 29,
    tempRange: 7,
  },
  "Guntur, AP": {
    baseDemand: 1800,
    tempCoef: 73,
    humidCoef: 7,
    windCoef: -10,
    lat: 16.3,
    lng: 80.44,
    timezone: "IST",
    baseTemp: 29,
    tempRange: 7,
  },
  "Kurnool, AP": {
    baseDemand: 1200,
    tempCoef: 74,
    humidCoef: 5,
    windCoef: -11,
    lat: 15.83,
    lng: 78.04,
    timezone: "IST",
    baseTemp: 29,
    tempRange: 8,
  },
  "Kadapa, AP": {
    baseDemand: 1000,
    tempCoef: 74,
    humidCoef: 5,
    windCoef: -10,
    lat: 14.47,
    lng: 78.82,
    timezone: "IST",
    baseTemp: 29,
    tempRange: 8,
  },
  "Rajahmundry, AP": {
    baseDemand: 1200,
    tempCoef: 70,
    humidCoef: 8,
    windCoef: -9,
    lat: 17.01,
    lng: 81.8,
    timezone: "IST",
    baseTemp: 29,
    tempRange: 6,
  },
  "Tirupati, AP": {
    baseDemand: 900,
    tempCoef: 70,
    humidCoef: 6,
    windCoef: -10,
    lat: 13.63,
    lng: 79.42,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 6,
  },

  // --- Tamil Nadu ---
  "Coimbatore, TN": {
    baseDemand: 2800,
    tempCoef: 65,
    humidCoef: 6,
    windCoef: -10,
    lat: 11.02,
    lng: 76.96,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 4,
  },
  "Madurai, TN": {
    baseDemand: 2000,
    tempCoef: 68,
    humidCoef: 6,
    windCoef: -9,
    lat: 9.93,
    lng: 78.12,
    timezone: "IST",
    baseTemp: 30,
    tempRange: 4,
  },
  "Tiruchirappalli, TN": {
    baseDemand: 1800,
    tempCoef: 68,
    humidCoef: 6,
    windCoef: -9,
    lat: 10.79,
    lng: 78.7,
    timezone: "IST",
    baseTemp: 30,
    tempRange: 4,
  },
  "Salem, TN": {
    baseDemand: 1500,
    tempCoef: 66,
    humidCoef: 5,
    windCoef: -9,
    lat: 11.66,
    lng: 78.15,
    timezone: "IST",
    baseTemp: 29,
    tempRange: 5,
  },
  "Tirunelveli, TN": {
    baseDemand: 1100,
    tempCoef: 67,
    humidCoef: 7,
    windCoef: -9,
    lat: 8.73,
    lng: 77.7,
    timezone: "IST",
    baseTemp: 29,
    tempRange: 4,
  },
  "Ambattur, TN": {
    baseDemand: 900,
    tempCoef: 68,
    humidCoef: 8,
    windCoef: -8,
    lat: 13.11,
    lng: 80.15,
    timezone: "IST",
    baseTemp: 30,
    tempRange: 4,
  },
  "Erode, TN": {
    baseDemand: 1000,
    tempCoef: 67,
    humidCoef: 5,
    windCoef: -9,
    lat: 11.34,
    lng: 77.73,
    timezone: "IST",
    baseTemp: 29,
    tempRange: 5,
  },
  "Avadi, TN": {
    baseDemand: 700,
    tempCoef: 68,
    humidCoef: 8,
    windCoef: -8,
    lat: 13.11,
    lng: 80.1,
    timezone: "IST",
    baseTemp: 30,
    tempRange: 4,
  },

  // --- Karnataka ---
  "Mysuru, KA": {
    baseDemand: 1800,
    tempCoef: 60,
    humidCoef: 5,
    windCoef: -11,
    lat: 12.31,
    lng: 76.66,
    timezone: "IST",
    baseTemp: 23,
    tempRange: 5,
  },
  "Hubballi-Dharwad, KA": {
    baseDemand: 1400,
    tempCoef: 67,
    humidCoef: 4,
    windCoef: -12,
    lat: 15.36,
    lng: 75.14,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 6,
  },
  "Mangaluru, KA": {
    baseDemand: 1200,
    tempCoef: 62,
    humidCoef: 10,
    windCoef: -9,
    lat: 12.91,
    lng: 74.86,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 4,
  },
  "Belgaum, KA": {
    baseDemand: 1100,
    tempCoef: 65,
    humidCoef: 5,
    windCoef: -11,
    lat: 15.85,
    lng: 74.5,
    timezone: "IST",
    baseTemp: 24,
    tempRange: 6,
  },
  "Gulbarga, KA": {
    baseDemand: 900,
    tempCoef: 74,
    humidCoef: 4,
    windCoef: -12,
    lat: 17.33,
    lng: 76.82,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 9,
  },
  "Shimoga, KA": {
    baseDemand: 700,
    tempCoef: 62,
    humidCoef: 7,
    windCoef: -10,
    lat: 13.93,
    lng: 75.56,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 5,
  },
  "Tumkur, KA": {
    baseDemand: 700,
    tempCoef: 63,
    humidCoef: 5,
    windCoef: -11,
    lat: 13.34,
    lng: 77.1,
    timezone: "IST",
    baseTemp: 24,
    tempRange: 5,
  },
  "Bellary, KA": {
    baseDemand: 800,
    tempCoef: 74,
    humidCoef: 4,
    windCoef: -12,
    lat: 15.14,
    lng: 76.92,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 9,
  },

  // --- Kerala ---
  "Kochi, KL": {
    baseDemand: 2200,
    tempCoef: 58,
    humidCoef: 10,
    windCoef: -8,
    lat: 9.93,
    lng: 76.26,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 3,
  },
  "Thiruvananthapuram, KL": {
    baseDemand: 1800,
    tempCoef: 58,
    humidCoef: 10,
    windCoef: -8,
    lat: 8.52,
    lng: 76.94,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 3,
  },
  "Kozhikode, KL": {
    baseDemand: 1200,
    tempCoef: 58,
    humidCoef: 10,
    windCoef: -8,
    lat: 11.25,
    lng: 75.78,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 3,
  },
  "Thrissur, KL": {
    baseDemand: 1000,
    tempCoef: 58,
    humidCoef: 10,
    windCoef: -8,
    lat: 10.53,
    lng: 76.22,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 3,
  },
  "Kollam, KL": {
    baseDemand: 900,
    tempCoef: 58,
    humidCoef: 10,
    windCoef: -8,
    lat: 8.88,
    lng: 76.59,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 3,
  },

  // --- West Bengal ---
  "Howrah, WB": {
    baseDemand: 2500,
    tempCoef: 65,
    humidCoef: 7,
    windCoef: -12,
    lat: 22.59,
    lng: 88.31,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Durgapur, WB": {
    baseDemand: 1400,
    tempCoef: 66,
    humidCoef: 7,
    windCoef: -12,
    lat: 23.48,
    lng: 87.31,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Asansol, WB": {
    baseDemand: 1400,
    tempCoef: 66,
    humidCoef: 7,
    windCoef: -12,
    lat: 23.68,
    lng: 86.99,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Siliguri, WB": {
    baseDemand: 1100,
    tempCoef: 62,
    humidCoef: 8,
    windCoef: -11,
    lat: 26.72,
    lng: 88.43,
    timezone: "IST",
    baseTemp: 24,
    tempRange: 11,
  },
  "Rajpur Sonarpur, WB": {
    baseDemand: 800,
    tempCoef: 64,
    humidCoef: 7,
    windCoef: -12,
    lat: 22.44,
    lng: 88.39,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Bhatpara, WB": {
    baseDemand: 700,
    tempCoef: 64,
    humidCoef: 7,
    windCoef: -12,
    lat: 22.87,
    lng: 88.41,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Panihati, WB": {
    baseDemand: 700,
    tempCoef: 64,
    humidCoef: 7,
    windCoef: -12,
    lat: 22.69,
    lng: 88.37,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "South Dumdum, WB": {
    baseDemand: 700,
    tempCoef: 64,
    humidCoef: 7,
    windCoef: -12,
    lat: 22.63,
    lng: 88.4,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Kamarhati, WB": {
    baseDemand: 700,
    tempCoef: 64,
    humidCoef: 7,
    windCoef: -12,
    lat: 22.67,
    lng: 88.37,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Bardhaman, WB": {
    baseDemand: 900,
    tempCoef: 65,
    humidCoef: 7,
    windCoef: -12,
    lat: 23.23,
    lng: 87.86,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Kulti, WB": {
    baseDemand: 600,
    tempCoef: 65,
    humidCoef: 7,
    windCoef: -12,
    lat: 23.73,
    lng: 86.85,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },
  "Kharagpur, WB": {
    baseDemand: 700,
    tempCoef: 64,
    humidCoef: 7,
    windCoef: -11,
    lat: 22.33,
    lng: 87.32,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 10,
  },

  // --- Jharkhand ---
  "Ranchi, JH": {
    baseDemand: 1800,
    tempCoef: 70,
    humidCoef: 6,
    windCoef: -12,
    lat: 23.36,
    lng: 85.33,
    timezone: "IST",
    baseTemp: 24,
    tempRange: 11,
  },
  "Dhanbad, JH": {
    baseDemand: 1600,
    tempCoef: 68,
    humidCoef: 7,
    windCoef: -12,
    lat: 23.8,
    lng: 86.43,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 11,
  },
  "Jamshedpur, JH": {
    baseDemand: 1800,
    tempCoef: 70,
    humidCoef: 7,
    windCoef: -12,
    lat: 22.8,
    lng: 86.19,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 11,
  },
  "Bokaro, JH": {
    baseDemand: 1000,
    tempCoef: 68,
    humidCoef: 7,
    windCoef: -12,
    lat: 23.67,
    lng: 85.98,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 11,
  },

  // --- Odisha ---
  "Bhubaneswar, OD": {
    baseDemand: 2000,
    tempCoef: 70,
    humidCoef: 8,
    windCoef: -10,
    lat: 20.3,
    lng: 85.82,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 8,
  },
  "Cuttack, OD": {
    baseDemand: 1400,
    tempCoef: 70,
    humidCoef: 8,
    windCoef: -10,
    lat: 20.46,
    lng: 85.88,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 8,
  },
  "Brahmapur, OD": {
    baseDemand: 700,
    tempCoef: 68,
    humidCoef: 8,
    windCoef: -9,
    lat: 19.31,
    lng: 84.79,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 7,
  },
  "Gopalpur, OD": {
    baseDemand: 500,
    tempCoef: 67,
    humidCoef: 9,
    windCoef: -9,
    lat: 19.26,
    lng: 84.89,
    timezone: "IST",
    baseTemp: 28,
    tempRange: 6,
  },

  // --- Bihar ---
  "Patna, BR": {
    baseDemand: 2500,
    tempCoef: 82,
    humidCoef: 7,
    windCoef: -16,
    lat: 25.6,
    lng: 85.1,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 13,
  },
  "Gaya, BR": {
    baseDemand: 800,
    tempCoef: 80,
    humidCoef: 6,
    windCoef: -14,
    lat: 24.8,
    lng: 85.0,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 13,
  },
  "Muzaffarpur, BR": {
    baseDemand: 800,
    tempCoef: 81,
    humidCoef: 7,
    windCoef: -15,
    lat: 26.12,
    lng: 85.39,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 13,
  },
  "Bhagalpur, BR": {
    baseDemand: 700,
    tempCoef: 80,
    humidCoef: 7,
    windCoef: -14,
    lat: 25.24,
    lng: 87.01,
    timezone: "IST",
    baseTemp: 26,
    tempRange: 13,
  },

  // --- Chhattisgarh ---
  "Raipur, CG": {
    baseDemand: 2000,
    tempCoef: 74,
    humidCoef: 6,
    windCoef: -12,
    lat: 21.25,
    lng: 81.63,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 11,
  },
  "Bhilai, CG": {
    baseDemand: 1500,
    tempCoef: 74,
    humidCoef: 6,
    windCoef: -12,
    lat: 21.21,
    lng: 81.38,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 11,
  },
  "Korba, CG": {
    baseDemand: 700,
    tempCoef: 73,
    humidCoef: 6,
    windCoef: -11,
    lat: 22.35,
    lng: 82.7,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 11,
  },
  "Bilaspur, CG": {
    baseDemand: 900,
    tempCoef: 74,
    humidCoef: 6,
    windCoef: -12,
    lat: 22.08,
    lng: 82.15,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 11,
  },

  // --- Punjab & Haryana ---
  "Ludhiana, PB": {
    baseDemand: 2800,
    tempCoef: 85,
    humidCoef: 5,
    windCoef: -17,
    lat: 30.9,
    lng: 75.86,
    timezone: "IST",
    baseTemp: 23,
    tempRange: 17,
  },
  "Amritsar, PB": {
    baseDemand: 2000,
    tempCoef: 84,
    humidCoef: 5,
    windCoef: -17,
    lat: 31.64,
    lng: 74.87,
    timezone: "IST",
    baseTemp: 22,
    tempRange: 17,
  },
  "Jalandhar, PB": {
    baseDemand: 1800,
    tempCoef: 84,
    humidCoef: 5,
    windCoef: -17,
    lat: 31.33,
    lng: 75.58,
    timezone: "IST",
    baseTemp: 23,
    tempRange: 17,
  },
  "Patiala, PB": {
    baseDemand: 1200,
    tempCoef: 84,
    humidCoef: 5,
    windCoef: -16,
    lat: 30.34,
    lng: 76.39,
    timezone: "IST",
    baseTemp: 24,
    tempRange: 17,
  },
  "Faridabad, HR": {
    baseDemand: 2500,
    tempCoef: 88,
    humidCoef: 6,
    windCoef: -18,
    lat: 28.41,
    lng: 77.31,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 15,
  },
  "Gurgaon, HR": {
    baseDemand: 3000,
    tempCoef: 88,
    humidCoef: 6,
    windCoef: -18,
    lat: 28.46,
    lng: 77.03,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 15,
  },
  "Rohtak, HR": {
    baseDemand: 900,
    tempCoef: 87,
    humidCoef: 5,
    windCoef: -17,
    lat: 28.89,
    lng: 76.59,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 16,
  },
  "Chandigarh, CH": {
    baseDemand: 1800,
    tempCoef: 83,
    humidCoef: 5,
    windCoef: -16,
    lat: 30.74,
    lng: 76.79,
    timezone: "IST",
    baseTemp: 23,
    tempRange: 16,
  },

  // --- Assam & Northeast ---
  "Guwahati, AS": {
    baseDemand: 1500,
    tempCoef: 65,
    humidCoef: 9,
    windCoef: -10,
    lat: 26.14,
    lng: 91.74,
    timezone: "IST",
    baseTemp: 24,
    tempRange: 9,
  },
  "Dispur, AS": {
    baseDemand: 600,
    tempCoef: 65,
    humidCoef: 9,
    windCoef: -10,
    lat: 26.14,
    lng: 91.78,
    timezone: "IST",
    baseTemp: 24,
    tempRange: 9,
  },
  "Agartala, TR": {
    baseDemand: 500,
    tempCoef: 63,
    humidCoef: 9,
    windCoef: -9,
    lat: 23.83,
    lng: 91.28,
    timezone: "IST",
    baseTemp: 25,
    tempRange: 8,
  },
  "Imphal, MN": {
    baseDemand: 400,
    tempCoef: 60,
    humidCoef: 8,
    windCoef: -9,
    lat: 24.82,
    lng: 93.94,
    timezone: "IST",
    baseTemp: 22,
    tempRange: 10,
  },
  "Itanagar, AR": {
    baseDemand: 200,
    tempCoef: 55,
    humidCoef: 9,
    windCoef: -8,
    lat: 27.1,
    lng: 93.62,
    timezone: "IST",
    baseTemp: 20,
    tempRange: 9,
  },
  "Kohima, NL": {
    baseDemand: 200,
    tempCoef: 52,
    humidCoef: 8,
    windCoef: -8,
    lat: 25.67,
    lng: 94.11,
    timezone: "IST",
    baseTemp: 18,
    tempRange: 9,
  },
  "Aizawl, MZ": {
    baseDemand: 200,
    tempCoef: 52,
    humidCoef: 9,
    windCoef: -8,
    lat: 23.72,
    lng: 92.72,
    timezone: "IST",
    baseTemp: 20,
    tempRange: 9,
  },

  // --- Himalayan / Hill States ---
  "Srinagar, JK": {
    baseDemand: 1500,
    tempCoef: 70,
    humidCoef: 5,
    windCoef: -12,
    lat: 34.08,
    lng: 74.8,
    timezone: "IST",
    baseTemp: 13,
    tempRange: 18,
  },
  "Jammu, JK": {
    baseDemand: 1100,
    tempCoef: 78,
    humidCoef: 5,
    windCoef: -13,
    lat: 32.73,
    lng: 74.87,
    timezone: "IST",
    baseTemp: 22,
    tempRange: 17,
  },
  "Dehradun, UK": {
    baseDemand: 1200,
    tempCoef: 72,
    humidCoef: 6,
    windCoef: -12,
    lat: 30.32,
    lng: 78.03,
    timezone: "IST",
    baseTemp: 20,
    tempRange: 14,
  },
  "Shimla, HP": {
    baseDemand: 500,
    tempCoef: 60,
    humidCoef: 6,
    windCoef: -10,
    lat: 31.1,
    lng: 77.17,
    timezone: "IST",
    baseTemp: 12,
    tempRange: 14,
  },
  "Gangtok, SK": {
    baseDemand: 200,
    tempCoef: 50,
    humidCoef: 7,
    windCoef: -8,
    lat: 27.33,
    lng: 88.61,
    timezone: "IST",
    baseTemp: 14,
    tempRange: 10,
  },

  // --- Telangana ---
  "Warangal, TS": {
    baseDemand: 1500,
    tempCoef: 72,
    humidCoef: 6,
    windCoef: -12,
    lat: 18.0,
    lng: 79.58,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 9,
  },
  "Nizamabad, TS": {
    baseDemand: 700,
    tempCoef: 72,
    humidCoef: 5,
    windCoef: -12,
    lat: 18.67,
    lng: 78.1,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 9,
  },

  // --- Goa ---
  "Panaji, GA": {
    baseDemand: 600,
    tempCoef: 58,
    humidCoef: 10,
    windCoef: -9,
    lat: 15.5,
    lng: 73.83,
    timezone: "IST",
    baseTemp: 27,
    tempRange: 4,
  },

  // --- Andaman ---
  "Port Blair, AN": {
    baseDemand: 200,
    tempCoef: 52,
    humidCoef: 11,
    windCoef: -8,
    lat: 11.66,
    lng: 92.74,
    timezone: "IST",
    baseTemp: 29,
    tempRange: 2,
  },
};

export const LOCALITIES = Object.keys(LOCALITY_PROFILES).sort((a, b) =>
  a.localeCompare(b),
);

function seededRandom(seed: number): number {
  const x = Math.sin(seed) * 10000;
  return x - Math.floor(x);
}

function generateWeather(locality: string, date: Date, seed: number) {
  const profile = LOCALITY_PROFILES[locality];
  const month = date.getMonth();
  const seasonalTemp =
    Math.sin(((month - 3) * Math.PI) / 6) * profile.tempRange;
  const temperature =
    profile.baseTemp + seasonalTemp + (seededRandom(seed) - 0.5) * 6;
  const monsoonHumid = month >= 5 && month <= 8 ? 20 : 0;
  const humidity =
    55 +
    monsoonHumid +
    Math.sin((month * Math.PI) / 3) * 15 +
    (seededRandom(seed + 1) - 0.5) * 20;
  const wind_speed = 10 + (seededRandom(seed + 2) - 0.5) * 18;
  return {
    temperature: Math.round(temperature * 10) / 10,
    humidity: Math.min(100, Math.max(20, Math.round(humidity))),
    wind_speed: Math.max(0, Math.round(wind_speed * 10) / 10),
  };
}

export function generateHistoricalData(locality: string): HistoricalRecord[] {
  const profile = LOCALITY_PROFILES[locality];
  if (!profile) return [];

  const records: HistoricalRecord[] = [];
  const start = new Date("2021-01-01");
  const end = new Date("2026-03-30");

  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    const dayOfYear = Math.floor(
      (d.getTime() - start.getTime()) / (1000 * 60 * 60 * 24),
    );
    const weather = generateWeather(locality, d, dayOfYear * 17 + 31);
    const dow = d.getDay();
    const isWeekend = dow === 0 || dow === 6;
    const weekendFactor = isWeekend ? 0.88 : 1.0;
    const noise = (seededRandom(dayOfYear * 13 + 7) - 0.5) * 300;
    const yearTrend = (d.getFullYear() - 2021) * 60;
    const demand =
      profile.baseDemand +
      profile.tempCoef * weather.temperature +
      profile.humidCoef * weather.humidity +
      profile.windCoef * weather.wind_speed +
      yearTrend +
      noise;

    const finalDemand = Math.max(800, Math.round(demand * weekendFactor));

    records.push({
      date: d.toISOString().split("T")[0],
      demand_mw: finalDemand,
      temperature: weather.temperature,
      humidity: weather.humidity,
      wind_speed: weather.wind_speed,
      locality,
    });
  }

  return records;
}

export function getLocalityProfile(locality: string) {
  return LOCALITY_PROFILES[locality];
}

export function getMonthlyAverages(records: HistoricalRecord[], year: number) {
  const filtered = records.filter((r) => r.date.startsWith(String(year)));
  const monthly: Record<number, { total: number; count: number }> = {};
  for (let m = 1; m <= 12; m++) monthly[m] = { total: 0, count: 0 };
  for (const r of filtered) {
    const m = Number.parseInt(r.date.split("-")[1]);
    monthly[m].total += r.demand_mw;
    monthly[m].count += 1;
  }
  const months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  return months.map((name, i) => ({
    month: name,
    avg_demand:
      monthly[i + 1].count > 0
        ? Math.round(monthly[i + 1].total / monthly[i + 1].count)
        : 0,
  }));
}

export function getLocalityStats(records: HistoricalRecord[]) {
  if (records.length === 0) return null;
  const demands = records.map((r) => r.demand_mw);
  return {
    avg_demand: Math.round(demands.reduce((a, b) => a + b, 0) / demands.length),
    peak_demand: Math.max(...demands),
    min_demand: Math.min(...demands),
    data_points: demands.length,
  };
}
